name: Upload code to ftp.endora.cz
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install FTP
        run: sudo apt-get update && sudo apt-get install -y lftp
      - name: Remove all files except vendor directory
        run: |
          shopt -s extglob
          rm -rf !(vendor)
      - name: Upload to FTP
        run: |
          lftp -c "set ssl:verify-certificate no; open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} medvidek.endora.cz && mirror -R --exclude-glob vendor . /"
